# Generated by Django 3.2.10 on 2022-01-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport_data',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('airport_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('temperature', models.CharField(max_length=100)),
                ('dewpoint', models.CharField(max_length=200)),
                ('pressure', models.CharField(max_length=200)),
                ('winds', models.CharField(max_length=200)),
                ('visibility', models.CharField(max_length=200)),
                ('ceiling', models.CharField(max_length=200)),
                ('clouds', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'airports2',
            },
        ),
    ]
